// Generated from the Apps Script alias packs (Code.gs + IG Brand search.gs + Pipeline Scanner.gs).
// Existing entries always win, matching the load-order semantics of the original.
// Add new brands to STATIC_ALIASES; learned aliases are merged at runtime by the worker.

export const STATIC_ALIASES: Record<string, string> = {
  "drinkag1": "AG1",
  "athletic greens": "AG1",
  "athleticgreens": "AG1",
  "ag1": "AG1",
  "notion.so": "Notion",
  "notion": "Notion",
  "squarespace": "Squarespace",
  "skillshare": "Skillshare",
  "brilliant.org": "Brilliant",
  "brilliant": "Brilliant",
  "betterhelp": "BetterHelp",
  "better help": "BetterHelp",
  "nordvpn": "NordVPN",
  "expressvpn": "ExpressVPN",
  "surfshark": "Surfshark",
  "audible": "Audible",
  "hellofresh": "HelloFresh",
  "hello fresh": "HelloFresh",
  "teuxdeux": "TeuxDeux",
  "teux deux": "TeuxDeux",
  "dbrand": "dbrand",
  "casetify": "CASETiFY",
  "trade coffee": "Trade Coffee",
  "tradecoffee": "Trade Coffee",
  "fellow": "Fellow",
  "raycon": "Raycon",
  "ridge": "Ridge",
  "ridge wallet": "Ridge",
  "ridge wallets": "Ridge",
  "manscaped": "Manscaped",
  "curiositystream": "CuriosityStream",
  "curiosity stream": "CuriosityStream",
  "nebula": "Nebula",
  "established titles": "Established Titles",
  "babbel": "Babbel",
  "grammarly": "Grammarly",
  "keeper": "Keeper",
  "keeper security": "Keeper Security",
  "functi0n": "Function of Beauty",
  "function of beauty": "Function of Beauty",
  "aura": "Aura",
  "auraframes": "Aura Frames",
  "aura frames": "Aura Frames",
  "micro center": "Micro Center",
  "microcenter": "Micro Center",
  "newegg": "Newegg",
  "corsair": "Corsair",
  "ekwb": "EKWB",
  "ek water blocks": "EKWB",
  "seasonic": "Seasonic",
  "be quiet": "be quiet!",
  "be quiet!": "be quiet!",
  "bequiet": "be quiet!",
  "ifixit": "iFixit",
  "thermal grizzly": "Thermal Grizzly",
  "thermalgrizzly": "Thermal Grizzly",
  "lianli": "Lian Li",
  "lian li": "Lian Li",
  "pcspecialist": "PCSpecialist",
  "glasswire": "GlassWire",
  "glass wire": "GlassWire",
  "ting": "Ting",
  "noctua": "Noctua",
  "phanteks": "Phanteks",
  "deepcool": "DeepCool",
  "cooler master": "Cooler Master",
  "coolermaster": "Cooler Master",
  "msi": "MSI",
  "asus": "ASUS",
  "evga": "EVGA",
  "gigabyte": "Gigabyte",
  "asrock": "ASRock",
  "crucial": "Crucial",
  "kingston": "Kingston",
  "samsung": "Samsung",
  "western digital": "Western Digital",
  "wd": "Western Digital",
  "seagate": "Seagate",
  "sabrent": "Sabrent",
  "teamgroup": "TeamGroup",
  "team group": "TeamGroup",
  "pny": "PNY",
  "bambu lab": "Bambu Lab",
  "bambulab": "Bambu Lab",
  "bambu": "Bambu Lab",
  "helixsleep": "Helix Sleep",
  "helix": "Helix Sleep",
  "helix sleep": "Helix Sleep",
  "falcon-nw": "Falcon Northwest",
  "falcon northwest": "Falcon Northwest",
  "sbird": "Scentbird",
  "scentbird": "Scentbird",
  "frctl": "Fractal Design",
  "fractal": "Fractal Design",
  "fractal design": "Fractal Design",
  "geekompc": "Geekom",
  "geekom": "Geekom",
  "myskylight": "Skylight",
  "skylight": "Skylight",
  "fonusmobile": "Fonus",
  "fonus": "Fonus",
  "inmoxr": "INMO",
  "inmo": "INMO",
  "fifinemicrophone": "Fifine",
  "fifine": "Fifine",
  "centralcomputer": "Central Computers",
  "central computers": "Central Computers",
  "opera gx": "Opera",
  "opera": "Opera",
  "andaseat": "AndaSeat",
  "noblechairs": "Noblechairs",
  "steampowered": "Steam",
  "xreal": "XREAL",
  "xrealonepro": "XREAL",
  "xreal1s": "XREAL",
  "factor": "Factor",
  "factor75": "Factor",
  "woojer": "Woojer",
  "lenovo": "Lenovo",
  "qualcomm": "Qualcomm",
  "dropbox": "Dropbox",
  "incogni": "Incogni",
  "reolink": "Reolink",
  "analogue": "Analogue",
  "sfbags": "SF Bags",
  "playstation": "PlayStation",
  "pac": "PacSun",
  "pacsun": "PacSun",
  "ikea": "IKEA",
  "ikeausa": "IKEA",
  "calvinklein": "Calvin Klein",
  "polestar": "Polestar",
  "merrell": "Merrell",
  "adidas": "Adidas",
  "airbnb": "Airbnb",
  "fancyfeast": "Fancy Feast",
  "drmartens": "Dr. Martens",
  "disneyplus": "Disney+",
  "jins": "JINS",
  "brooklinen": "Brooklinen",
  "logitech": "Logitech",
  "stanley1913": "Stanley",
  "adobe": "Adobe",
  "nike": "Nike",
  "lululemon": "lululemon",
  "gymshark": "Gymshark",
  "skims": "SKIMS",
  "uniqlo": "UNIQLO",
  "zara": "Zara",
  "madewell": "Madewell",
  "everlane": "Everlane",
  "allbirds": "Allbirds",
  "newbalance": "New Balance",
  "hoka": "HOKA",
  "patagonia": "Patagonia",
  "northface": "The North Face",
  "thenorthface": "The North Face",
  "dyson": "Dyson",
  "ourplace": "Our Place",
  "caraway": "Caraway",
  "hexclad": "HexClad",
  "ruggable": "Ruggable",
  "wayfair": "Wayfair",
  "westelm": "West Elm",
  "potterybarn": "Pottery Barn",
  "homedepot": "The Home Depot",
  "lowes": "Lowe's",
  "sephora": "Sephora",
  "ulta": "Ulta Beauty",
  "glossier": "Glossier",
  "rarebeauty": "Rare Beauty",
  "fenty": "Fenty Beauty",
  "fentybeauty": "Fenty Beauty",
  "cerave": "CeraVe",
  "olaplex": "Olaplex",
  "yeti": "YETI",
  "owala": "Owala",
  "hydroflask": "Hydro Flask",
  "gopro": "GoPro",
  "garmin": "Garmin",
  "peloton": "Peloton",
  "whoop": "WHOOP",
  "ouraring": "Oura",
  "amazon": "Amazon",
  "factormeals": "Factor",
  "doordash": "DoorDash",
  "ubereats": "Uber Eats",
  "chipotle": "Chipotle",
  "starbucks": "Starbucks",
  "dunkin": "Dunkin'",
  "liquidiv": "Liquid I.V.",
  "kobo": "Kobo",
  "rakutenkobo": "Kobo",
  "soltech": "Soltech",
  "cozyearth": "Cozy Earth",
  "barbour": "Barbour",
  "viture": "VITURE",
  "sihoo": "SIHOO",
  "hbada": "Hbada",
  "laifen": "Laifen",
  "laifentech": "Laifen",
  "govee": "Govee",
  "ringconn": "RingConn",
  "secretlab": "Secretlab",
  "dreo": "DREO",
  "oralb": "Oral-B",
  "gillette": "Gillette",
  "volvo": "Volvo",
  "raybanmeta": "Ray-Ban Meta",
  "fellowproducts": "Fellow",
  "lmnt": "LMNT",
  "drinklmnt": "LMNT",
  "olipop": "OLIPOP",
  "drinkolipop": "OLIPOP",
  "poppi": "poppi",
  "drinkpoppi": "poppi",
  "cirkul": "Cirkul",
  "drinkcirkul": "Cirkul",
  "air up": "air up",
  "airup": "air up",
  "waterdrop": "Waterdrop",
  "liquid iv": "Liquid I.V.",
  "liquid i v": "Liquid I.V.",
  "sodastream": "SodaStream",
  "spindrift": "Spindrift",
  "owalalife": "Owala",
  "larq": "LARQ",
  "livelarq": "LARQ",
  "lifestraw": "LifeStraw",
  "grayl": "GRAYL",
  "hydrant": "Hydrant",
  "drinkhydrant": "Hydrant",
  "waterboy": "Waterboy",
  "nuun": "Nuun",
  "dripdrop": "DripDrop",
  "brumate": "BruMate",
  "hydro flask": "Hydro Flask"
};

export const MASS_SPONSOR_BRANDS: string[] = [
  "squarespace",
  "skillshare",
  "brilliant",
  "audible",
  "nordvpn",
  "expressvpn",
  "surfshark",
  "betterhelp",
  "hellofresh",
  "nebula",
  "curiositystream",
  "established titles",
  "raid shadow legends",
  "raycon",
  "ridge",
  "manscaped",
  "babbel",
  "grammarly",
  "function of beauty",
  "keeper security"
];

export const JUNK_DOMAINS: string[] = [
  "youtube",
  "instagram",
  "tiktok",
  "facebook",
  "twitter",
  "x",
  "pinterest",
  "reddit",
  "snapchat",
  "linkedin",
  "threads",
  "patreon",
  "ko-fi",
  "buymeacoffee",
  "paypal",
  "venmo",
  "google",
  "apple",
  "spotify",
  "amazon",
  "bit",
  "linktr",
  "youtu",
  "goo",
  "amzn",
  "tinyurl",
  "bitly",
  "creativecommons",
  "commons",
  "wikimedia",
  "wikipedia",
  "mailto",
  "javascript",
  "static",
  "cdn",
  "assets",
  "media",
  "content",
  "upload",
  "image",
  "embed",
  "player",
  "widget",
  "tracking",
  "analytics",
  "share",
  "plugin",
  "twitch",
  "streamlabs",
  "discord",
  "floatplane",
  "playstation",
  "xbox",
  "nintendo",
  "steampowered",
  "steam",
  "epicgames",
  "soundcloud",
  "shrsl",
  "shareasale",
  "linksynergy",
  "awin",
  "avantlink",
  "skimresources",
  "rstyle",
  "howl",
  "mavely",
  "geni",
  "sovrn",
  "redirectingat",
  "anrdoezrs",
  "dpbolvw",
  "kqzyfj",
  "jdoqocy",
  "tkqlhce",
  "pjtra",
  "pntra",
  "pntrs",
  "gopjn",
  "affilimate",
  "tomshardware",
  "videocardz"
];
